export const siteConfig = {
  name: "Siham Demami",
  title: "Siham Demami — Data Science & Web Developer",
  description: "Master's student in Data Science and Intelligent Systems with expertise in web development, data analytics, and machine learning. Based in Fès, Morocco.",
  url: "https://siham-portfolio.vercel.app",
  ogImage: "/og-image.png",
  links: {
    email: "siham.demami1@gmail.com",
    linkedin: "https://linkedin.com/in/sihamdemami",
    github: "https://github.com/sihamdemami",
    phone: "+212 6 XX XX XX XX", // Update with real number if needed
  },
  keywords: [
    "Data Science",
    "Web Development",
    "Machine Learning",
    "AI",
    "Python",
    "React",
    "Next.js",
    "Django",
    "SpringBoot",
    "Full Stack Developer",
    "Morocco",
    "Fès",
  ],
}

export const heroContent = {
  name: "Siham Demami",
  title: "Data Science & Web Developer",
  tagline: "Turning Data into Intelligent Web Experiences",
  description: "Master's student in Data Science and Intelligent Systems based in Fès, Morocco. Specializing in web development, data analytics, and machine learning with experience in Python, Java, SpringBoot, and React.",
}

export const skills = {
  programming: [
    "Python",
    "Java",
    "C",
    "C++",
    "SQL",
    "HTML",
    "CSS",
    "PHP",
    "JavaScript",
    "TypeScript",
  ],
  frameworks: [
    "React",
    "Next.js",
    "SpringBoot",
    "Django",
    "Laravel",
    "Node.js",
    "JEE",
  ],
  aiDataScience: [
    "PySpark",
    "Scikit-learn",
    "LangChain",
    "HuggingFace",
    "Machine Learning",
    "Deep Learning",
    "CNN",
    "GNN",
  ],
  databases: [
    "MySQL",
    "SQLServer",
    "Neo4j",
    "MongoDB",
  ],
  tools: [
    "Linux",
    "Git",
    "Docker",
    "Vercel",
    "AWS",
    "Enterprise Architect",
    "phpMyAdmin",
    "SSAS",
    "SSIS",
    "SSRS",
  ],
}

export const experiences = [
  {
    company: "MG2 Engineering - Capgemini Engineering",
    position: "End-of-Study Intern - Smart Web Application Development",
    location: "Fès, Morocco",
    startDate: "Feb 2025",
    endDate: "Jul 2025",
    current: true,
    description: [
      "Built smart web app with chatbot using Microsoft 365 tools for intelligent document retrieval and task automation",
      "Implemented secure OAuth authentication, KPI dashboards, and personalized UI",
      "Reduced internal search time by 60% and increased user engagement by 45%",
    ],
    technologies: [
      "Python",
      "Django",
      "React",
      "LangChain",
      "HuggingFace",
      "OAuth",
      "Microsoft Graph API",
    ],
    impact: {
      searchTime: "-60%",
      engagement: "+45%",
    },
  },
  {
    company: "Educational Center Mobdie",
    position: "Full-Stack Developer Intern",
    location: "Fès, Morocco",
    startDate: "Apr 2023",
    endDate: "Jun 2023",
    current: false,
    description: [
      "Developed web app for syndicate and resident management serving 500+ users",
      "Designed responsive UI with React and efficient Laravel backend APIs",
      "Reduced data processing time by 40%",
    ],
    technologies: ["Laravel", "React", "PHP", "MySQL"],
    impact: {
      users: "500+",
      processingTime: "-40%",
    },
  },
  {
    company: "Faculty of Sciences and Techniques, Fès",
    position: "Student Developer - Academic Projects",
    location: "Fès, Morocco",
    startDate: "2023",
    endDate: "2024",
    current: false,
    description: [
      "Traffic Sign Recognition System using CNN - achieved 92% accuracy",
      "Coronary Heart Disease Prediction using PySpark and Pandas - 88% precision",
      "Full-stack apps for Employee, Task, and Resource Management using SpringBoot, Java, SQL",
      "Data warehouse cube using SQLServer, SSAS, SSIS, SSRS",
    ],
    technologies: [
      "Python",
      "PySpark",
      "SpringBoot",
      "Java",
      "SQL",
      "SQLServer",
      "CNN",
      "Machine Learning",
    ],
    impact: {
      accuracy: "92%",
      precision: "88%",
    },
  },
]

export const projects = [
  {
    id: 1,
    name: "Smart Chatbot Web Application",
    description: "Enterprise chatbot built with LangChain and Microsoft Graph API — reduced internal search time by 60% through intelligent document retrieval and task automation. Features OAuth authentication and real-time KPI dashboards.",
    image: "/images/chatbot.png",
    category: ["AI", "Web"],
    technologies: [
      "Python",
      "Django",
      "React",
      "LangChain",
      "HuggingFace",
      "OAuth",
      "Microsoft Graph API",
    ],
    linkSource: "https://github.com/sihamdemami",
    linkPreview: "https://github.com/sihamdemami",
    impact: "60% reduction in search time",
    featured: true,
  },
  {
    id: 2,
    name: "Traffic Sign Recognition System",
    description: "Deep learning application achieving 92% accuracy on real-time traffic sign detection using CNN architectures. Deployed model processes 30 frames per second for autonomous vehicle assistance.",
    image: "/images/traffic-sign.png",
    category: ["AI"],
    technologies: ["Python", "CNN", "TensorFlow", "OpenCV", "Deep Learning"],
    linkSource: "https://github.com/sihamdemami/Traffic-Sign-Recognition-Main-App",
    linkPreview: "https://github.com/sihamdemami/Traffic-Sign-Recognition-Main-App",
    impact: "92% accuracy, 30 FPS processing",
    featured: true,
  },
  {
    id: 3,
    name: "Coronary Heart Disease Predictor",
    description: "PySpark-powered ML application predicting 10-year CHD risk with 88% precision. Processes large-scale health datasets using distributed computing, enabling early intervention for at-risk patients.",
    image: "/images/heart-disease.png",
    category: ["Data Science"],
    technologies: ["Python", "PySpark", "Pandas", "Scikit-learn", "Machine Learning"],
    linkSource: "https://github.com/sihamdemami/Coronary-Heart-Disease-Prediction-PySpark",
    linkPreview: "https://github.com/sihamdemami/Coronary-Heart-Disease-Prediction-PySpark",
    impact: "88% precision on CHD prediction",
    featured: true,
  },
  {
    id: 4,
    name: "Syndicate Management Platform",
    description: "Full-stack web app serving 500+ residents with React frontend and PHP backend. Features include payment tracking, maintenance requests, and automated reporting — reducing admin workload by 70%.",
    image: "/images/syndicate.png",
    category: ["Web"],
    technologies: ["React", "PHP", "Laravel", "MySQL", "REST API"],
    linkSource: "https://github.com/sihamdemami/Syndicat_react",
    linkPreview: "https://github.com/sihamdemami/Syndicat_react",
    impact: "500+ users, 70% workload reduction",
    featured: true,
  },
  {
    id: 5,
    name: "Audio-Image Multimodal Classifier",
    description: "Advanced deep learning project combining audio and visual data streams for classification. Implemented fusion techniques achieving 15% higher accuracy than single-modality approaches.",
    image: "/images/multimodal.png",
    category: ["AI", "Data Science"],
    technologies: ["Python", "TensorFlow", "Keras", "CNN", "Deep Learning"],
    linkSource: "https://github.com/sihamdemami/Audio-Image-multimodal-Classification---Deep-Learning",
    linkPreview: "https://github.com/sihamdemami/Audio-Image-multimodal-Classification---Deep-Learning",
    impact: "15% accuracy improvement",
    featured: false,
  },
  {
    id: 6,
    name: "Molecular Graph Classification",
    description: "Graph Neural Network implementation for MUTAG dataset classification. Explored GNN and GCN architectures for molecular property prediction in drug discovery applications.",
    image: "/images/molecular.png",
    category: ["Data Science", "AI"],
    technologies: ["Python", "PyTorch", "GNN", "GCN", "Graph Theory"],
    linkSource: "https://github.com/sihamdemami/Graphe-Classification-MUTAG-GNN---GCN-",
    linkPreview: "https://github.com/sihamdemami/Graphe-Classification-MUTAG-GNN---GCN-",
    impact: "Drug discovery application",
    featured: false,
  },
  {
    id: 7,
    name: "Speech Recognition System",
    description: "Advanced speech recognition system using MFCC features and Hidden Markov Models for accurate voice-to-text conversion with real-time processing capabilities.",
    image: "/images/speech.png",
    category: ["AI"],
    technologies: ["Python", "MFCC", "HMM", "Signal Processing", "Machine Learning"],
    linkSource: "https://github.com/sihamdemami",
    linkPreview: "https://github.com/sihamdemami",
    impact: "Real-time speech processing",
    featured: false,
  },
]

export const aboutContent = {
  intro: "Hi, I'm Siham Demami — a passionate Master's student in Data Science and Intelligent Systems with a mission to build data-driven web applications that bridge AI and exceptional user experiences.",
  paragraphs: [
    "With hands-on experience spanning web development, machine learning, and data analytics, I thrive on transforming complex challenges into elegant, scalable solutions. From developing smart chatbots that slash search times by 60% to architecting full-stack platforms serving hundreds of users, I'm driven by measurable impact.",
    "My toolkit includes Python, Java, React, SpringBoot, and cutting-edge ML frameworks like LangChain and HuggingFace. Whether it's deep learning models for healthcare prediction or enterprise web applications with real-time dashboards, I combine technical rigor with creative problem-solving to deliver solutions that matter.",
    "Currently seeking opportunities where I can leverage my dual expertise in data science and web development to create intelligent, user-centric applications.",
  ],
  education: [
    {
      degree: "Master's Degree in Data Science and Intelligent Systems",
      school: "Faculty of Sciences and Techniques, Fès",
      year: "2023 - 2025",
      description: "Specializing in machine learning, data analytics, and intelligent systems",
    },
    {
      degree: "Bachelor's Degree in Computer Engineering",
      school: "Faculty of Sciences and Techniques, Fès",
      year: "2020 - 2023",
      description: "Foundation in software engineering, algorithms, and web development",
    },
  ],
  image: "/images/siham.jpg",
}

export const navLinks = [
  { label: "Home", href: "#home" },
  { label: "Experience", href: "#experience" },
  { label: "Projects", href: "#projects" },
  { label: "About", href: "#about" },
  { label: "Contact", href: "#contact" },
]
